---
apiVersion: v2
appVersion: 0.9.2
description: baikal helm package
name: baikal
version: 1.1.1
kubeVersion: ">=1.16.0-0"
keywords:
  - baikal
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/baikal
icon: https://avatars.githubusercontent.com/u/28524376?s=400&v=4
sources:
  - https://github.com/baikal/baikal-docker
maintainers:
  - name: baikal
    email: baikal@baikal.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: mariadb
    repository: https://akarthik10.github.io/charts
    version: 1.0.3
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
