---
apiVersion: v2
appVersion: 10.5.16
description: mariadb helm package
name: mariadb
version: 1.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - mariadb
home: https://github.com/akarthik10/charts/tree/master/charts/stable/mariadb
icon: https://mariadb.org/icon
sources:
  - https://github.com/linuxserver/docker-mariadb
maintainers:
  - name: mariadb
    email: mariadb@mariadb.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
