#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: linuxserver/mariadb
  # -- image tag
  # @default -- chart.appVersion
  tag: 10.5.16
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [mariadb documentation](https://mariadb.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: dbname
  MYSQL_USER: dbuser
  MYSQL_PASSWORD: dbpass

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
        primary: false
      mysql:
        enabled: true
        primary: true
        port: 3306
        protocol: TCP


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /usr/bin/env
          - bash
          - -c
          - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /usr/bin/env
          - bash
          - -c
          - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /usr/bin/env
          - bash
          - -c
          - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /config
